localdb:
  image: postgres:11.2
  ports:
    - "5432:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=postgresDb
    - POSTGRES_PASSWORD=db1234
    - POSTGRES_DB=db_postgres

testdb:
  image: postgres:11.2
  ports:
    - "5433:5432"
  volumes:
    - ./db/dumps:/app-db-dumps
  environment:
    - POSTGRES_USER=postgresDb_test
    - POSTGRES_PASSWORD=db1234
    - POSTGRES_DB=db_postgres_test